#!/usr/bin/env bash

# 判断 acme.sh 是否存在
if [ ! -f "$HOME/.acme.sh/acme.sh" ]; then
    echo "acme.sh not found, installing..."
    curl https://get.acme.sh | sh
fi

usage() {
    echo "Usage: $0 --domain <domain_name> [--dns <dns_provider>]"
    echo "Options:"
    echo "  --domain <domain_name> : Specify the domain name for which SSL certificate is to be generated."
    echo "  --dns <dns_provider>   : Specify the DNS provider. Default is 'dns_cf' (Cloudflare)."
    exit 1
}

# 默认 DNS 提供商
dns_provider="dns_cf"

# 解析命令行参数
while [ $# -gt 0 ]; do
    key="$1"
    case $key in
        --domain)
        domain="$2"
        shift
        ;;
        --dns)
        dns_provider="$2"
        shift
        ;;
        *)
        usage
        ;;
    esac
    shift
done

if [ -z "$domain" ]; then
    echo "Error: Domain name not specified."
    usage
fi

echo "Generating SSL certificate for domain: $domain using DNS provider: $dns_provider"

# 设置默认 CA
~/.acme.sh/acme.sh --set-default-ca --server letsencrypt

# 生成证书
~/.acme.sh/acme.sh --issue --dns "$dns_provider" -d "$domain" -d "*.$domain" --dnssleep 300 --force

# 安装证书
mkdir -p "$HOME/ssl/"

# 删除已有 Secret
if kubectl get secret tls-"$domain" >/dev/null 2>&1; then
    echo "Secret tls-$domain already exists, deleting..."
    kubectl delete secret tls-"$domain"
fi

# 创建新的 Secret
kubectl create secret tls tls-"$domain" --cert="$HOME/ssl/$domain.crt" --key="$HOME/ssl/$domain.key"

# 安装证书并更新 Secret
~/.acme.sh/acme.sh --install-cert -d "$domain" --key-file "$HOME/ssl/$domain.key" --cert-file "$HOME/ssl/$domain.crt" --reloadcmd "kubectl delete secret tls-$domain; kubectl create secret tls tls-$domain --cert=$HOME/ssl/$domain.crt --key=$HOME/ssl/$domain.key"
